version: "3"

services:
  mongodb:
    image: mongo
    ports:
      - "27017"
    networks:
      - fin-network
    volumes:
      - mongodb_data:/data/db

  financial-helper:
    build:
      context: ./
    ports:
      - "3001:3001"
    networks:
      - fin-network
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017
      NUBANK_INTEGRATION_URL: http://nodeapp:3000
      APP_PORT: 3001

networks:
  fin-network:
    driver: bridge

volumes:
  mongodb_data:
